# Generated by Django 5.2.5 on 2025-08-25 17:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
