# Generated by Django 5.2.5 on 2025-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
