# Generated by Django 5.2.5 on 2025-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_imagem_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
