# Generated by Django 5.2.5 on 2025-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_pagina_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Logo do Site', max_length=100)),
                ('imagem', models.ImageField(upload_to='logo/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo do Site',
                'verbose_name_plural': 'Logo do Site',
            },
        ),
    ]
