# Generated by Django 5.2.5 on 2025-11-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrosséis',
            },
        ),
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='carrossel/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da imagem')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carrossel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='posts.carrossel')),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Imagens do Carrossel',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
