# Generated by Django 5.2.5 on 2026-01-21 20:27

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cpf',
            field=models.CharField(max_length=14, validators=[posts.models.validar_cpf], verbose_name='CPF'),
        ),
    ]
